server {
    listen 80;
    server_name shin.students.nomorepartiessbs.ru;

    location / {
                proxy_pass http://localhost:3000; # Перенаправляем запросы на порт 3000
                proxy_http_version 1.1; # Задаёт версию HTTP для прокси
                proxy_set_header Upgrade $http_upgrade; # Необходим для проксирования WebSocket-соединений
                proxy_set_header Connection 'upgrade';  # Необходим для проксирования WebSocket-соединений 
                proxy_set_header Host $host; # Содержит адрес домена, на который пришёл запрос
                proxy_cache_bypass $http_upgrade;
    }
}