version: "3.3"
services:

  db:
    restart: always
    image: postgres:15.2
    environment:
      POSTGRES_USER: prac1
      POSTGRES_PASSWORD: prac1
      POSTGRES_DB: prac1
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432