version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - DATABASE_URL=postgres://prac1:prac1@db:5432/prac1

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: prac1
      POSTGRES_PASSWORD: prac1
      POSTGRES_DB: prac1
    ports:
      - "5432:5432"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root@example.com
      PGADMIN_DEFAULT_PASSWORD: rootT
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge