services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ghcr.io/your-username/film-react-nest-frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ghcr.io/your-username/film-react-nest-backend:latest
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - DATABASE_URL=postgres://prac1:prac1@db:5432/prac1

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: prac1
      POSTGRES_PASSWORD: prac1
      POSTGRES_DB: prac1
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data: